/**
 * @file Browser dashboard renderer.
 * @description Fetches a generated report and renders safe, accessible DOM without HTML injection.
 * @exports No public exports; loaded by dashboard/index.html.
 * @data report is generated by src/cli.ts; all text enters the DOM through textContent.
 */
import type { LabReport, ScenarioResult, TimelineEntry } from '../src/reporting/report-model.ts';

const statusElement = requiredElement('overall-status');
const summaryElement = requiredElement('summary');
const scenariosElement = requiredElement('scenarios');

try {
  const response = await fetch('/lab-report.json');
  if (!response.ok) {
    throw new Error(`report request failed with ${response.status}`);
  }
  const report = (await response.json()) as LabReport;
  renderReport(report);
} catch (error: unknown) {
  statusElement.classList.add('status-failure');
  statusElement.textContent = error instanceof Error ? error.message : 'Unable to load report';
}

function renderReport(report: LabReport): void {
  const allPassed = report.summary.failed === 0;
  statusElement.classList.add(allPassed ? 'status-success' : 'status-failure');
  statusElement.replaceChildren(
    textElement('span', allPassed ? 'ALL SCENARIOS PASSED' : 'ATTENTION REQUIRED', 'status-label'),
    textElement('strong', `${report.summary.passed} / ${report.summary.total}`, 'status-value'),
    textElement(
      'span',
      `Generated ${new Date(report.generatedAt).toLocaleString()}`,
      'status-time',
    ),
  );

  const node = report.snapshot[0];
  const summaryCards: ReadonlyArray<readonly [string, string]> = [
    ['Node status', node?.online === true ? 'Online' : 'Offline'],
    ['Birth sequence', String(node?.birthSequence ?? '—')],
    ['Accepted messages', String(report.statistics.accepted)],
    [
      'Detected anomalies',
      String(report.statistics.duplicateMessages + report.statistics.outOfOrder),
    ],
  ];
  summaryElement.replaceChildren(
    ...summaryCards.map(([label, value]) => {
      const card = document.createElement('article');
      card.className = 'summary-card';
      card.append(textElement('p', label, 'card-label'), textElement('p', value, 'card-value'));
      return card;
    }),
  );

  scenariosElement.replaceChildren(...report.scenarios.map(renderScenario));
}

function renderScenario(scenario: ScenarioResult): HTMLElement {
  const article = document.createElement('article');
  article.className = `scenario-card ${scenario.passed ? 'scenario-pass' : 'scenario-fail'}`;

  const headingRow = document.createElement('div');
  headingRow.className = 'scenario-heading';
  headingRow.append(
    textElement('h3', scenario.title),
    textElement('span', scenario.passed ? 'PASS' : 'FAIL', 'scenario-badge'),
  );
  article.append(headingRow, textElement('p', scenario.purpose, 'scenario-purpose'));

  const timeline = document.createElement('ol');
  timeline.className = 'timeline';
  timeline.setAttribute('aria-label', `${scenario.title} event timeline`);
  timeline.append(...scenario.timeline.map(renderTimelineEntry));
  article.append(timeline);

  const details = document.createElement('details');
  const summary = document.createElement('summary');
  summary.textContent = 'Measured observations';
  const list = document.createElement('ul');
  for (const observation of scenario.observations) {
    const item = document.createElement('li');
    item.textContent = observation;
    list.append(item);
  }
  details.append(summary, list);
  article.append(details);
  return article;
}

function renderTimelineEntry(entry: TimelineEntry): HTMLLIElement {
  const item = document.createElement('li');
  item.className = `timeline-item timeline-${entry.status}`;
  item.append(
    textElement('span', String(entry.offset + 1).padStart(2, '0'), 'timeline-index'),
    textElement('strong', entry.event, 'timeline-event'),
    textElement('span', entry.detail, 'timeline-detail'),
  );
  return item;
}

function requiredElement(id: string): HTMLElement {
  const element = document.getElementById(id);
  if (element === null) {
    throw new Error(`dashboard element #${id} is missing`);
  }
  return element;
}

function textElement<K extends keyof HTMLElementTagNameMap>(
  tag: K,
  text: string,
  className?: string,
): HTMLElementTagNameMap[K] {
  const element = document.createElement(tag);
  element.textContent = text;
  if (className !== undefined) {
    element.className = className;
  }
  return element;
}
